### ISSUE TITLE
Macro $SERVICEGROUPNAME$ is not filled

### ISSUE THREAD

**Issue by VladimirBilik** [naemon/naemon-core#103]
I'm writing own notification script _send_notification_ which uses the $SERVICEGROUPNAME$ macro. I've just discovered that this macro is not filled with real value, it returns just '$SERVICEGROUPNAME$' string.
Other macros are OK.

Using naemon-core 1.0.0.

This is an extract from my debug:

```
[1426074272.722132] [2048.1] [pid=12332] **** BEGIN MACRO PROCESSING ***********
[1426074272.722138] [2048.1] [pid=12332] Processing: 
'$USER100$/send_notification 
--object='$ARG1$' 
--type='$ARG2$' 
--n_hostname='$HOSTNAME$' 
--n_hostdisplayname='$HOSTDISPLAYNAME$' 
--n_hostalias='$HOSTALIAS$' 
...
--n_servicegroupname='$SERVICEGROUPNAME$' 
--n_servicegroupnames='$SERVICEGROUPNAMES$' "

[1426074272.722881] [2048.1] [pid=12332]   Done.  Final output: 
'/usr/local/naemon/libexec-gtsnx/send_notification 
--object='service' 
--type='sms' 
--n_hostname='NAEMON' 
--n_hostdisplayname='NAEMON' 
--n_hostalias='NAEMON process' 
...
--n_servicegroupname='$SERVICEGROUPNAME$' 
--n_servicegroupnames='' 
...
[1426074272.722921] [2048.1] [pid=12332] **** END MACRO PROCESSING *************
```

**Comment by ageric** [comment]
Humm, I should think SERVICEGROUPNAME is obsoleted. We did that with some macros that weren't implemented and didn't make sense. The reason SERVICEGROUPNAME doesn't make sense is that there's no way to list a "primary" servicegroup for a service. In your case, the service also doesn't appear to be a member of any servicegroups at all, since the SERVICEGROUPNAMES (with the trailing S) is empty.

**Comment by VladimirBilik** [comment]
After years..... 
I can live without it now, so it is OK.
