### ISSUE TITLE
State OK should be always HARD

### ISSUE THREAD

**Issue by dirtyren** [naemon/naemon-core#205]
I came across a behavior today that  when a Host recovered, naemon logged OK SOFT

[1505505309] HOST ALERT: dirtyal2;UP;SOFT;7;oi neoson 294850828

 For availability reports that differentiate SOFT and HARD states, this host would still be DOWN in HARD state.
  Host recovered while in DOWN SOFT, maybe that's why it logged UP SOFT.
  Another thing, although naemon logger OK SOFT, livestatus shows the host in HARD STATE, so, naemon set the host to HARD, but logged SOFT.
  Should we fix this?

[1505505222] HOST ALERT: dirtyal2;DOWN;SOFT;1;oi neoson 294850828
[1505505246] HOST ALERT: dirtyal2;DOWN;SOFT;3;oi neoson 294850828
[1505505261] HOST ALERT: dirtyal2;DOWN;SOFT;5;oi neoson 294850828
[1505505309] HOST ALERT: dirtyal2;UP;SOFT;7;oi neoson 294850828

  Tks.

**Comment by sni** [comment]
Which availability report is that. I think that should be fixed there. If a host or service was in a soft state and recovers, this is a soft recovery and should be logged accordingly. After the recovery the host/service is in a Hard ok state. Only the recovery itself is soft. OK states are always hard.
Doing availability calculation based on hard states only should also work straight forward, because naemon will log a hard recovery if it was a hard down.
Anyway, doing availability calculation, all recoverys should be considered.

Here is an example: http://www.naemon.org/documentation/usersguide/statetypes.html#example

**Comment by dirtyren** [comment]
Tks @sni , you are right, I had't occurred to me that the host did not went to a HARD state, off cource, is recovered from a SOFT DOWN.
   Thanks again.
